# Clippy Configuration

# Allow specific lints
allow = [
    "clippy::too_many_arguments",
    "clippy::type_complexity",
    "clippy::module_name_repetitions",
]

# Deny specific lints
deny = [
    "clippy::unwrap_used",
    "clippy::expect_used",
    "clippy::panic",
    "clippy::unimplemented",
    "clippy::todo",
]

# Set specific lint levels
warn = [
    "clippy::pedantic",
    "clippy::nursery",
    "clippy::cargo",
]

# Configure specific lints
doc_markdown = ["Wine", "DXVK", "Vulkan", "Direct3D"]
cognitive-complexity-threshold = 25
too-many-arguments-threshold = 7
type-complexity-threshold = 300
module-name-repetitions-threshold = 20 